# .github/workflows/test.yml
name: Test Workflow

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "✅ Workflow is working!"
